### ISSUE TITLE
get_top_correls Method

### ISSUE THREAD

**Issue by Jasonli1997** [AviFelman/py-cryptocompare#1]
Is there a better way to do `get_top_correls` without enterprise access?

The way I did it was to input a list with a bunch of coins and run correlations against the selected asset and picked the top five currencies. So I was wondering if there was a better way to do it.

**Comment by AviFelman** [comment]
For creating lists easily, I don't think there is. Probably best to manually create different lists of assets to reference. Personally Have not found a better way. 

Also, I think the code for top correls is quite complicated for some reason. I just pushed a new version of it to the repo.
